# Test de moyenne bilatéral - T test simulation (Monte Carlo)
# Objectif: Estimation de puissance 
# dans le cas: 2 échantillons indépendants de même variance 
# connue s, et de moyennes respectives 0 et meand.
# NB: les tailles des échantillons ne sont pas nécessairement
# égales: on les note n1 et n2
# Clear environment
rm(list=ls())

#-----------------------------------------------------------------------
# Paramètres de la simulation
#-----------------------------------------------------------------------


# Number of runs
runs = 10000

# Sample sizes (for each group)
n1 = 20
n2 = 20
# Difference between the means
# no difference to test the alpha level (type I errors)
meand0 = 0
# non null to test how often the existing effect is found (power)
meand = 0.1

# Standard deviation of both samples
s = 0.1

# Erreur de 1ère espèce
alpha = 0.05

#---------------------------------------------------
# t-test simulations (Monte-Carlo)
#---------------------------------------------------

ttest_MC_samevar<-function(runs, meand, n1, n2, s, alpha){
    
  # Independent variable (predictor)
  x = c(
    rep(1,n1),	# group 1
    rep(2,n2)	# group 2
  )
  x = factor(x)
  
  # Perform runs (with stochastic sampling)
  tval = numeric(runs) # to store resulting t statistics
  tval_hand = numeric(runs) # to store resulting t statistics (computed by hand)
  pval = numeric(runs) # to store resulting p-values
  for (r in 1:runs) {
    # Generate random independent samples with normal distributions
    # for the dependent variable (predicted)
    y = c(
      rnorm(n1,mean=0,sd=s),
      rnorm(n2,mean=meand,sd=s)
    )
    
    # Run model : on stocke les t-statistics et p-values
    # du modèle généré par R.
    model = t.test(y~x, var.equal=TRUE)
    tval[r] = model$statistic
    pval[r] = model$p.value
    
    # Hand-made equivalent to compute the t statistic
    # (will produce the same value as model$statistic)
    # DV for each group
    y1 = y[x==1]
    y2 = y[x==2]
    # Pooled standard deviation
    s12 = sqrt((sd(y1)^2+sd(y2)^2)/(n1+n2-2))
    tval_hand[r] = (mean(y1)-mean(y2))/(s12*sqrt((1/n1)+(1/n2)))
  }
  
  # Display the resulting statistics
  res = data.frame(
    t_statistic=tval,
    t_statistic_hand=tval_hand,
    p_value=pval
  )
  head(res,10)
  
  # Histograms for the observed t statistic on independent samples
  hist(tval,freq=FALSE,breaks=100)
  # Curve for the theoretical distribution for independent samples
  # (if mean = 0)
  s_range = seq(min(tval),max(tval),length.out=100)
  lines(s_range,dt(s_range,n1+n1-2))
  # if the histogram and curve match,
  # this means we cannot differentiate the results at chance level)
  
  # Directly exploit the pvalues generated by the model
  # to get the power of type I error rate (depending on meand value)
  # p5_model devrait tendre vers 0.05 si meand = 0
  # p5_model nous donne la puissance du test si meand != 0
  nb = sum(pval<alpha)
  # --> signifie que si meand = 0, on conclue à tort un effet à un ratio p5_model
  # si meand != 0, on affirme à raison un effet à un ratio p5_model
  p5_model = nb/runs
  
  # Compute the ratio of type I errors (should be <0.5)
  # equivalent to what precedes (to help you understand the computations)
  # (using the t statistic table/function)
  # p5_hand devrait etre égal à p5_model
  thr_low = qt(alpha/2,n1+n2-2,lower.tail=T)
  thr_upp = qt(alpha/2,n1+n2-2,lower.tail=F)
  nb = sum(tval<thr_low | tval>thr_upp)
  p5_hand = nb/runs
  
  # On calcule la puissance théorique (analytique) du t-test avec le package power:
  # NB: Dans le cas n1 = n2 = n, on devrait avoir p5_package = p5_model = p5_hand.
  p5_package = power.t.test(n=(n1+n2)/2, d = meand/s, sig.level = alpha, type = "two.sample", alternative = "two.sided")$power
  
  # Add these results to the global table
  results = data.frame(
    n1=n1,
    n2=n2,
    mean_diff=meand,
    sd=s,
    runs=runs,
    p5_model=p5_model,
    p5_hand=p5_hand,
    p5_package=p5_package 
  )
  results
}
ttest_MC_samevar(runs, meand0, n1, n2, s, alpha)
# If meand=0, we expect the proportion of p-values<0.05 to be roughly at 0.05 (type I error rate)
# If meand!=0, we expect the proportion of p-values<0.05 to be the highest possible (power)
