# Test de moyenne - T test simulation (Monte Carlo)
# Objectif: Estimation de puissance 
# dans le cas: 2 échantillons appariés

# Clear environment
rm(list=ls())

#-----------------------------------------------------------------------
# Paramètres de la simulation
#-----------------------------------------------------------------------

# Taille des échantillons pilotes
npilote = 40


# Taille des tirages pour Monte-Carlo.
n = 50
# Number of runs for MC
runs = 1000


# Difference between the means
# no difference to test the alpha level (type I errors)
meand = 0 
# non null to test how often the existing effect is found (power)
meand = 0.04

# Standard deviation of samples
s1 = 0.1
s2 = 0.05

# correlation factor
cf = 0.8

# Erreur de 1ère espèce
alpha = 0.05


#---------------------------------------------------
#                     pilote 
#---------------------------------------------------



pilote_ttest_paired<-function(npilote, meand, s1, s2, cf)
{
  # On simule 2 échantillons "réels"
  # tels que: leur différence de moyenne est meand,
  # les standard error des echantillons sont s1 et s2,
  # et le facteur de corrélation est cf.
  congruent = rnorm(npilote,mean = 0,sd = s1)
  # Dans le cas apparié, on suppose que Y = a + bX + eps,
  # où eps est une normale centrée. On a donc:
  a = meand
  # puis var(Y) = b²var(X) + var(eps), et
  # cf = b/(s1s2)
  b = cf*(s1*s2)
  sd_eps = sqrt(s2^2-b^2*s1^2)  
  eps = rnorm(npilote,mean = 0,sd = sd_eps)
  incongruent = a + b*congruent + eps
  # On estime les paramètres du pilote
  mean1 = mean(congruent)
  mean2 = mean(incongruent)
  ecart_type_congruent = sd(congruent)
  ecart_type_incongruent = sd(incongruent)
  cf_estime = cor(congruent, incongruent)
  # On retourne l'approximation de l'étude pilote
  return (c(mean1, mean2, ecart_type_congruent, ecart_type_incongruent, cf_estime))
}





#---------------------------------------------------
# t-test simulations (Monte-Carlo)
#---------------------------------------------------

ttest_normal<-function(runs, n, pilote, alpha){
  
  # On récupère les paramètres du pilote
  mean1 = pilote[1]
  mean2 = pilote[2]
  s1 = pilote[3]
  s2 = pilote[4]
  cf = pilote[5]
  
  # Independent variable (predictor)
  x = c(
    rep(1,n)	# group 
  )
  x = factor(x)
  
  # Perform runs (with stochastic sampling)
  tval = numeric(runs) # to store resulting t statistics
  tval_hand = numeric(runs) # to store resulting t statistics (computed by hand)
  pval = numeric(runs) # to store resulting p-values
  
  sz = sqrt(s1^2+s2^2-(2*cf*s1*s2))
  
  for (r in 1:runs) {
    # Generate random independent samples with normal distributions
    # for the dependent variable (predicted)
    y = c(
      rnorm(n,mean=mean2-mean1,sd=sz)
    )
    
    # Run model : on stocke les t-statistics et p-values
    # du modèle généré par R.
    model = t.test(y)
    tval[r] = model$statistic
    pval[r] = model$p.value
    
    # Hand-made equivalent to compute the t statistic
    # (will produce the same value as model$statistic)
    # DV for group
    y1 = y[x==1]
    # Pooled standard deviation
    s12 = sd(y1)
    tval_hand[r] = mean(y1)/(s12/sqrt(n))
  }
  
  # Display the resulting statistics
  res = data.frame(
    t_statistic=tval,
    t_statistic_hand=tval_hand,
    p_value=pval
  )
  head(res,10)
  
  # Histograms for the observed t statistic on independent samples
  hist(tval,freq=FALSE,breaks=100)
  # Curve for the theoretical distribution for independent samples
  # (if mean = 0)
  s_range = seq(min(tval),max(tval),length.out=100)
  lines(s_range,dt(s_range,n+n-2))
  # if the histogram and curve match,
  # this means we cannot differentiate the results at chance level)
  
  # Directly exploit the pvalues generated by the model
  # to get the power of type I error rate (depending on meand value)
  # p5_model devrait tendre vers 0.05 si meand = 0
  # p5_model nous donne la puissance du test si meand != 0
  nb = sum(pval<alpha)
  # --> signifie que si meand = 0, on conclue à tort un effet à un ratio p5_model
  # si meand != 0, on affirme à raison un effet à un ratio p5_model
  p5_model = nb/runs
  
  # Compute the ratio of type I errors (should be <0.5)
  # equivalent to what precedes (to help you understand the computations)
  # (using the t statistic table/function)
  # p5_hand devrait etre égal à p5_model
  thr_low = qt(alpha/2,n+n-2,lower.tail=T)
  thr_upp = qt(alpha/2,n+n-2,lower.tail=F)
  nb = sum(tval<thr_low | tval>thr_upp)
  p5_hand = nb/runs
  
  # On calcule la puissance théorique (analytique) du t-test avec le package power:
  # NB: Dans le cas n1 = n2 = n, on devrait avoir p5_package = p5_model = p5_hand.
  p5_package = power.t.test(n=n, d = (mean2-mean1)/sz, sig.level = alpha, type = "paired", alternative = "two.sided")$power
  
  # Add these results to the global table
  results = data.frame(
    n=n,
    mean_diff=mean2-mean1,
    s1=s1,
    s2 = s2,
    runs=runs,
    p5_model=p5_model,
    p5_hand=p5_hand,
    p5_package=p5_package 
  )
  results
}
pilote = pilote_ttest_paired(npilote, meand, s1, s2, cf)
ttest_normal(runs, n, pilote, alpha)
# If meand=0, we expect the proportion of p-values<0.05 to be roughly at 0.05 (type I error rate)
# If meand!=0, we expect the proportion of p-values<0.05 to be the highest possible (power)

